name: Label issues
on:
  issues:
    types:
      - reopened
      - opened
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Definir Label Padrão
        run: echo "LABELS=triage" >> $GITHUB_ENV

      - name: Verificar se a Issue menciona 'bug'
        run: |
          ISSUE_BODY=$(gh issue view "$NUMBER" --json body,title | jq -r '.body + " " + .title' | tr '[:upper:]' '[:lower:]')
          if echo "$ISSUE_BODY" | grep -q "bug"; then
            echo "LABELS=triage,bug" >> $GITHUB_ENV
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}

      - name: Adicionar Label na Issue
        run: gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}

