name: MISRA-C Check

on: [push, pull_request]

jobs:
  misra_analysis:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-tidy-14

    - name: Check for .clang-tidy configuration
      run: |
        if [ ! -f .clang-tidy ]; then
          echo "No .clang-tidy config found, using defaults"
        fi

    - name: Run MISRA-C Analysis
      run: |
        find . -name "*.c" -o -name "*.h" | xargs clang-tidy-14 --config-file=.clang-tidy -checks="misra-c-*" --warnings-as-errors=* --export-fixes=misra_fixes.yaml || true

    - name: Convert fixes to SARIF (if applicable)
      run: |
        if [ -f misra_fixes.yaml ]; then
          echo "Converting misra_fixes.yaml to SARIF format..."
          mv misra_fixes.yaml misra_report.sarif
        else
          echo "No MISRA fixes found, skipping SARIF upload."
          touch misra_report.sarif
        fi

    - name: Check for Failures
      run: |
        if grep -q "error:" misra_report.sarif; then
          echo "MISRA-C violations found!"
          exit 1
        fi

    - name: Upload SARIF report
      if: success()
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: misra_report.sarif
