name: MISRA-C Check

on: [push, pull_request]

jobs:
  misra_analysis:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies (if needed)
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-tidy-14 bear

    - name: Generate Compilation Database
      run: |
        if [ -f Makefile ]; then
          echo "Generating compilation database..."
          bear -- make || { echo "Failed to generate compile_commands.json"; exit 1; }
        else
          echo "No Makefile found. Ensure the project can be built."
          exit 1
        fi

    - name: Ensure .clang-tidy Exists
      run: |
        if [ ! -f .clang-tidy ]; then
          echo "Creating default .clang-tidy config"
          echo "Checks: 'misra-c-*'" > .clang-tidy
        fi

    - name: Run MISRA-C Analysis
      run: |
        find . -name "*.c" -o -name "*.h" | xargs -r clang-tidy-14 -p compile_commands.json --config-file=.clang-tidy --export-fixes=misra_report.sarif

    - name: Check for Failures
      run: |
        if grep -q "error:" misra_report.sarif; then
          echo "MISRA-C violations found!"
          exit 1
        fi

    - name: Upload SARIF report (optional, for advanced integration)
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: misra_report.sarif





